version: '3'
services:
  
  # PHP Service
  text:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: text-api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: text
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - text-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: text-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8083:80"
      - "8445:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - text-network

# Docker Networks
networks:
  text-network:
    driver: bridge