version: '3'
services:
  
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - note-network

  # Nginx Service for F1301 Note
  webserver:
    image: nginx:alpine
    container_name: note-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - note-network

# Docker Networks
networks:
  note-network:
    driver: bridge
